config/routes.rb
Rails.application.routes.draw do
  resources :pessoas
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pessoa.rb
class Pessoa < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pessoas_controller.rb
class PessoasController < ApplicationController
  before_action :set_pessoa, only: %i[ show edit update destroy ]

  # GET /pessoas or /pessoas.json
  def index
    @pessoas = Pessoa.all
  end

  # GET /pessoas/1 or /pessoas/1.json
  def show
  end

  # GET /pessoas/new
  def new
    @pessoa = Pessoa.new
  end

  # GET /pessoas/1/edit
  def edit
  end

  # POST /pessoas or /pessoas.json
  def create
    @pessoa = Pessoa.new(pessoa_params)

    respond_to do |format|
      if @pessoa.save
        format.html { redirect_to @pessoa, notice: "Este formulário foi salvo com sucesso." }
        format.json { render :show, status: :created, location: @pessoa }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pessoas/1 or /pessoas/1.json
  def update
    respond_to do |format|
      if @pessoa.update(pessoa_params)
        format.html { redirect_to @pessoa, notice: "Este formulário foi atualizado com sucesso." }
        format.json { render :show, status: :ok, location: @pessoa }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pessoas/1 or /pessoas/1.json
  def destroy
    @pessoa.destroy
    respond_to do |format|
      format.html { redirect_to pessoas_url, notice: "Este registro foi excluido com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pessoa
      @pessoa = Pessoa.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pessoa_params
      params.require(:pessoa).permit(:Nome, :genero, :data_de_nascimento, :CPF, :Telefone, :Email, :Endereco, :Cidade, :Estado)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pessoas_helper.rb
module PessoasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Formulario</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pessoas/_form.html.erb
<%= form_with(model: pessoa) do |form| %>
  <% if pessoa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pessoa.errors.count, "error") %> prohibited this pessoa from being saved:</h2>

      <ul>
        <% pessoa.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<center>
  <fieldset>
    <div class="field">
      <%= form.label :Nome %>
        <%= form.text_field :Nome, required:"" %>
    </div>

    <div class="field">
      <%= form.label :Gênero %>
      <%= form.select :genero, [[""], ["Masculino"], ["Feminino"]] %>
    </div>

    <div class="field">
      <%= form.label :data_de_nascimento%>
      <input id="date_field" type="date" >
    </div>

    <div class="field">
      <%= form.label :CPF %>
      <%= form.text_field :CPF, placeholder:'123.456.789-00', title:"Digite um CPF no formato: xxx.xxx.xxx-xx", required:"" %>
      <input type="text" name="CPF" pattern="(\d{3}\.?\d{3}\.?\d{3}-?\d{2})|(\d{2}\.?\d{3}\.?\d{3}/?\d{4}-?\d{2})">
    </div>

    <div class="field">
      <%= form.label :Telefone %>
      <%= form.text_field :Telefone, placeholder:'(12) 91234-5678', pattern:"\([0-9]{2}\) [0-9]{4,6}-[0-9]{3,4}$", required:"" %>
    </div>

    <div class="field">
      <%= form.label :Email %>
      <%= form.email_field :Email, placeholder:'e-mail....@mail.com' , required:""%>
    </div>

    <div class="field">
      <%= form.label :Endereço %>
      <%= form.text_field :Endereco, required:"" %>
    </div>

    <div class="field">
      <%= form.label :Cidade %>
      <%= form.text_field :Cidade, required:"" %>
    </div>


    <div class="field">
      <%= form.label :Estado %>
      <%= form.select :Estado, [["---", "---"], ["Acre", "AC"], ["Alagoas", "AL"], ["Amapá", "AP"], ["Amazonas", "AM"], ["Bahia", "BA"], ["Ceará", "CE"], ["Espírito Santo", "ES"], ["Goiás", "GO"], ["Maranhão", "MA"], ["Mato Grosso", "MT"], ["Mato Grosso do Sul", "MS"], ["Minas Gerais", "MG"], ["Pará", "PA"], ["Paraíba", "PB"], ["Paraná", "PR"], ["Pernambuco", "PE"], ["Piauí", "PI"], ["Rio de Janeiro", "RJ"], ["Rio Grande do Norte", "RN"], ["Rio Grande do Sul", "RS"], ["Rondônia", "RO"], ["Roraima", "RR"], ["Santa Catarina", "SC"], ["São Paulo", "SP"], ["Sergipe", "SE"], ["Tocantins", "TO"], ["Distrito Federal", "DF"]] %>
    </div>
    
    <div class="actions">
      <%= form.submit %>
    </div>
    </center>
  </fieldset>
<% end %>

app/views/pessoas/edit.html.erb
<center>
<h1>Modificando o formulário</h1>
</center>
<%= render 'form', pessoa: @pessoa %>
<center>
<%= link_to 'Mostrar', @pessoa %> |
<%= link_to 'Voltar', pessoas_path %>
</center>

app/views/pessoas/index.html.erb
<p id="notice"><%= notice %></p>

  <center><h1>Confirmação de Dados</h1></center>

<center>
  <table border="3">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Gênero</th>
        <th>Data de Nascimento</th>
        <th>CPF</th>
        <th>Telefone</th>
        <th>E-mail</th>
        <th>Endereço</th>
        <th>Cidade</th>
        <th>Estado</th>
      </tr>
    </thead>

    <tbody>
      <% @pessoas.each do |pessoa| %>
        <tr>
          <td><%= pessoa.Nome %></td>
          <td><%= pessoa.genero %></td>
          <td><%= pessoa.data_de_nascimento %></td>
          <td><%= pessoa.CPF %></td>
          <td><%= pessoa.Telefone %></td>
          <td><%= pessoa.Email %></td>
          <td><%= pessoa.Endereco %></td>
          <td><%= pessoa.Cidade %></td>
          <td><%= pessoa.Estado %></td>
          <td><%= link_to 'Mostrar', pessoa %></td>
          <td><%= link_to 'Editar', edit_pessoa_path(pessoa) %></td>
          <td><%= link_to 'Detelar', pessoa, method: :delete, data: { confirm: 'Deseja excluir este registro?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
  <button>
    <%= link_to 'Preencha o formulário', new_pessoa_path %>
  </button>
</center>

app/views/pessoas/new.html.erb
<center>
<h1>Preencha o formulário</h1>
</center>
<%= render 'form', pessoa: @pessoa %>
<center>
<%= link_to 'Voltar', pessoas_path %>
</center>

app/views/pessoas/show.html.erb
<center>
<fieldset>
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @pessoa.Nome %>
</p>

<p>
  <strong>Gênero:</strong>
  <%= @pessoa.genero %>
</p>

<p>
  <strong>Data de nascimento:</strong>
  <%= @pessoa.data_de_nascimento %>
</p>

<p>
  <strong>CPF:</strong>
  <%= @pessoa.CPF %>
</p>

<p>
  <strong>Telefone(com DDD):</strong>
  <%= @pessoa.Telefone %>
</p>

<p>
  <strong>E-mail:</strong>
  <%= @pessoa.Email %>
</p>

<p>
  <strong>Endereço:</strong>
  <%= @pessoa.Endereco %>
</p>

<p>
  <strong>Cidade:</strong>
  <%= @pessoa.Cidade %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @pessoa.Estado %>
</p>

<%= link_to 'Editar', edit_pessoa_path(@pessoa) %> |
<%= link_to 'Voltar', pessoas_path %>
</fieldset>
</center>